---
- name: install httpd
  yum:
    name: httpd
    state: present


- name: open port 80
  ansible.posix.firewalld:
    zone: public
    port: 80/tcp
    permanent: true
    immediate: true
    state: enabled

- name: copy index.html
  copy:
    src: files/index.html
    dest: /var/www/html/index.html
 
- name: Start service httpd, if not started
  ansible.builtin.service:
    name: httpd
    state: started

